### ISSUE TITLE
Error argument passed  

### ISSUE THREAD

**Issue by cbillon** [moodleworkplace/moodle-tool_datewatch#1]
![2022-11-27_10-43-31](https://user-images.githubusercontent.com/3054194/204128788-f716a877-7998-4c13-bc3e-a59d04259c00.png)

Moodle-tool_datewatch/classes/observer.php line 37:
$tableid = $event->objectid ?? 0;
The null coalescing operator (??) has been added as syntactic sugar for the common case of needing to use a ternary in conjunction with [isset()](https://www.php.net/manual/en/function.isset.php). It returns its first operand if it exists and is not null; otherwise it returns its second operand.
If var is empty string , the result is not zero
Change line 37 to 
        if (empty($event->objectid)) {
           $tableid = 0;
        } else {
           $tableid = $event->objectid ?? 0;
        }
Thanks for your attention
Claude Billon

**Comment by marinaglancy** [comment]
Hi Claude, thanks for reporting it, sorry we did not pay attention to this issue before.

The property objectid is defined in the event class as having type int, although it is no strict type check. 

I think the best place to fix this issue will be in the block_cmanager plugin itself, in this line:

https://github.com/michael-milette/moodle-block_cmanager/blob/master/lib/course_lib.php#L98

that plugin should pass objectid as null or not pass it at all.

**Comment by marinaglancy** [comment]
actually, on the second thought I think we should fix it in tool_datewatch too, other plugins may also contain objecttable/objectid of incorrect type.

**Comment by marinaglancy** [comment]
This change was addressed under WP-4152 and will be included in the next release
